services:
    reveal-demo-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: reveal-demo-dev_c
        ports:
            - '7823:7823'
        volumes:
            - ./:/app
            - /app/node_modules
